### ISSUE TITLE
False Acolyte description

### ISSUE THREAD

**Issue by kennyrkun** [Erostey/Story#1]
How should we go about explaining the False Acolyte? Should he have his own file specifically for his time as the False Acolyte, or should we have a file specifically for Froggy where False Acolyte is an included section?

This won't really change anything about him, I'm just interested in how we should explain him. I think it would be better if there were just one file for Frogger specifically, where we just add sections since he's done so much in all of his roles. If we do go this road, it raises some other questions:
- will we use the same method to explain the others? 
- Should we have a file for every major player on the server? 
- What will define a major player?

**Comment by Auduceus** [comment]
Well, the False Acolyte was used as a nick name since, referring to him as soggy, doesn't sound... impactful I guess. I originally was just going to call him that in story context until he became the woodsman. If we can think of a different name perhaps we could put the False Acolyte title under it.

I think that explaining each player and having a sort of "backstory" or file of each character is a neat idea. It gives everyone a sort of importance and something to be entitled to. If someone has a lot of shit under their belt, we could just give them a loaded resume. So if they have multiple titles, we mention them and when they may have swapped to said titles. 

I would say that basically everyone that has done something of some importance or plays on the server at least every now and then is a "major player". This is mostly because our population is so small. If we do get to the point where we have a bunch of people, just go off of what would be important about that player? Where they a key player in a notable battle? Did they build a large and popular landmark? Stuff of that nature.

**Comment by kennyrkun** [comment]
So we should make a file for Frog and just have the False Acolyte section as a part of it? If we do that, we will do something similar with you.

**Comment by Auduceus** [comment]
Yes, should we keep the file name as “soggy” or change it to something else? It doesn’t really matter since no one else will really see it *and* it is his name.

**Comment by kennyrkun** [comment]
we'll go with Froggy
